baseurl = "/"
title = "My Hugo Site"
languageCode = "en-us"
disqusShortname = "your disqus shortname"
googleAnalytics = "your google analytics"
copyright = "Copyright (c) 2015 - 2017, blanK; all rights reserved."
MetaDataFormat = "yaml"
theme = "orange"
[author]
    name = "blanK"

[indexes]
    tag = "tags"
    topic = "topics"

[Params]
	DateFormat = "2006年01月02日"
